### ISSUE TITLE
Add more Demo data

### ISSUE THREAD

**Issue by caprenter** [Bjwebb/bookish#35]
We need some transactions, transaction revisions, business years, companies and probably more in the demo data

**Comment by Bjwebb** [comment]
@caprenter Did a little bit of work on this, that's now been merged in https://github.com/Bjwebb/bookish/pull/59

**Comment by caprenter** [comment]
Next tasks are to add demo transactions for each available transaction type.

**Comment by oldcreakyknees** [comment]
... been working on demo data today. Should I add task/progress to GitHub?

Almost finished a year's worth of input (bank, cash, expenses (receipts) 
and mileage) and deriving the various outputs.

Will try to put up on google drive, share and send an e-mail when I'm done.

Cheers, Des

**Comment by Bjwebb** [comment]
Demo spreadsheet has now been shared, and we're working on adding it as demo data to the application on this branch: https://github.com/Bjwebb/bookish/tree/demo-spreadsheet

**Comment by caprenter** [comment]
Invoices, Mileage, Bank and Cash demo data is now imported. See https://github.com/Bjwebb/bookish/pull/79

**Comment by Bjwebb** [comment]
This should now be visible on the demo at http://bookish.bjwebb.co.uk/
