### ISSUE TITLE
createdemodata command is not documented

### ISSUE THREAD

**Issue by Bjwebb** [Bjwebb/bookish#5]

**Comment by Bjwebb** [comment]
Since I created this issue, the command is now listed in the README at https://github.com/Bjwebb/bookish/blob/master/README.rst#local-demo---without-docker

Next steps are to add more information to the README and to improve the output of `python manage.py help createdemodata`

**Comment by caprenter** [comment]
What more needs to be done here? Is this a job for me?

**Comment by Bjwebb** [comment]
I think you volunteered to write words about what the command does back in November back when you were assigned. 

I think there's more we can write in terms of help text, but if it's not clear what needs doing, feel free to assign back to me.

**Comment by caprenter** [comment]
ok - I seem to remember back then that 'createdemodata' wasn't documented at all. So now we're at a stage where you can follow the readme, and install it. I'm happy with that.

So I think we're down to just:
 improve the output of python manage.py help createdemodata

I'd close this ticket and create a new one for that. Is that ok @Bjwebb

**Comment by Bjwebb** [comment]
Yes, that makes sense.
