### ISSUE TITLE
Labels for columns in David's google spreadsheet

### ISSUE THREAD

**Issue by oldcreakyknees** [Bjwebb/bookish#77]
https://docs.google.com/spreadsheets/d/1uXUlse4TMbw_EUhdMZbUtd2rTfw-u1mm8lxhlRv6ons/edit#gid=682345576

Questions in cells N4 and O4, responses in N3 and O3 resp - "Bank" worksheet

**Comment by caprenter** [comment]
I think I have my answers to this thanks, so closing the ticket
